import { useState } from "react";
import { entities } from "@/api/dbClient";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { FileDown, Loader2 } from "lucide-react";
import { jsPDF } from "jspdf";
import { useAuth } from "@/lib/AuthContext";

export default function StudentPerformancePDF({ teacher }) {
  const [open, setOpen] = useState(false);
  const [studentId, setStudentId] = useState("");
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");
  const { appPublicSettings } = useAuth();
  const schoolNameEn = appPublicSettings?.public_settings?.school_name_en || "EduTrack Model School";

  const generate = async () => {
    if (!studentId.trim()) return;
    setGenerating(true); setError("");

    // Fetch all data in parallel
    const [students, grades, attendance, activityPosts] = await Promise.all([
      entities.Student.filter({ student_id: studentId.trim() }),
      entities.StudentGrade.filter({ student_id: studentId.trim() }),
      entities.Attendance.filter({ student_id: studentId.trim() }),
      entities.ActivityPost.filter({ author_email: "" }), // all posts for activity count
    ]);

    if (students.length === 0) { setError("Student not found."); setGenerating(false); return; }
    const student = students[0];

    // Compute stats
    const pct = (g) => Math.round((g.score / (g.max_score || 100)) * 100);
    const avgGrade = grades.length ? Math.round(grades.reduce((s, g) => s + pct(g), 0) / grades.length) : null;
    const presentCount = attendance.filter(a => a.status === "present").length;
    const absentCount = attendance.filter(a => a.status === "absent").length;
    const lateCount = attendance.filter(a => a.status === "late").length;
    const attendancePct = attendance.length ? Math.round((presentCount / attendance.length) * 100) : student.attendance_score || 100;

    // Group grades by subject
    const bySubject = {};
    grades.forEach(g => {
      if (!bySubject[g.subject_name]) bySubject[g.subject_name] = [];
      bySubject[g.subject_name].push(g);
    });

    // Build PDF
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const W = doc.internal.pageSize.getWidth();
    let y = 0;

    // Header band
    doc.setFillColor(30, 42, 100);
    doc.rect(0, 0, W, 80, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Student Performance Report", 40, 38);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by ${teacher.full_name} · ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}`, 40, 58);
    doc.text(schoolNameEn, W - 40, 58, { align: "right" });
    y = 100;

    // Student info box
    doc.setFillColor(245, 247, 250);
    doc.roundedRect(30, y, W - 60, 80, 8, 8, "F");
    doc.setTextColor(30, 42, 100);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(student.full_name, 50, y + 26);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 90, 110);
    doc.text(`Student ID: ${student.student_id}`, 50, y + 44);
    doc.text(`Grade: ${student.grade}${student.section ? " · Section " + student.section : ""}`, 50, y + 58);
    if (student.parent_name) doc.text(`Parent: ${student.parent_name}`, 50, y + 72);

    // Summary stats on the right
    const statsX = W - 200;
    const drawStat = (label, value, color, offsetY) => {
      doc.setFillColor(...color);
      doc.roundedRect(statsX, y + offsetY, 160, 30, 4, 4, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(label, statsX + 10, y + offsetY + 12);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(value, statsX + 10, y + offsetY + 26);
    };
    if (avgGrade !== null) drawStat("Grade Average", `${avgGrade}%`, [52, 168, 83], 4);
    drawStat("Attendance Rate", `${attendancePct}%`, [66, 133, 244], 38);

    y += 100;

    // Section helper
    const sectionTitle = (title) => {
      y += 18;
      doc.setFillColor(30, 42, 100);
      doc.rect(30, y, 4, 18, "F");
      doc.setTextColor(30, 42, 100);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(title, 42, y + 13);
      y += 28;
    };

    // ── Attendance Section ──
    sectionTitle("Attendance Summary");
    const aCols = [["Total Records", attendance.length], ["Present", presentCount], ["Absent", absentCount], ["Late", lateCount], ["Attendance %", `${attendancePct}%`]];
    aCols.forEach(([label, val], i) => {
      const x = 30 + i * ((W - 60) / 5);
      const bw = (W - 60) / 5 - 6;
      const isGood = label === "Attendance %" ? attendancePct >= 85 : label === "Present";
      doc.setFillColor(isGood ? 232 : label === "Absent" ? 254 : 243, isGood ? 245 : label === "Absent" ? 226 : 246, isGood ? 233 : label === "Absent" ? 214 : 190);
      doc.roundedRect(x, y, bw, 44, 4, 4, "F");
      doc.setTextColor(80, 90, 110);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text(label, x + 6, y + 14);
      doc.setTextColor(30, 42, 100);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(String(val), x + 6, y + 36);
    });
    y += 60;

    // ── Grades Section ──
    if (grades.length > 0) {
      sectionTitle("Academic Grades");
      // Table header
      doc.setFillColor(30, 42, 100);
      doc.rect(30, y, W - 60, 22, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("Subject", 40, y + 15);
      doc.text("Term", 210, y + 15);
      doc.text("Score", 290, y + 15);
      doc.text("Percentage", 360, y + 15);
      doc.text("Grade", 450, y + 15);
      y += 22;

      let rowAlt = false;
      grades.forEach(g => {
        if (y > 750) { doc.addPage(); y = 40; }
        doc.setFillColor(rowAlt ? 248 : 255, rowAlt ? 249 : 255, rowAlt ? 252 : 255);
        doc.rect(30, y, W - 60, 20, "F");
        const p = pct(g);
        const scoreColor = p >= 85 ? [52, 168, 83] : p >= 70 ? [66, 133, 244] : p >= 50 ? [251, 188, 4] : [234, 67, 53];
        doc.setTextColor(60, 70, 90);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.text(g.subject_name || "", 40, y + 14);
        doc.text(g.term || "", 210, y + 14);
        doc.text(`${g.score}/${g.max_score || 100}`, 290, y + 14);
        doc.setTextColor(...scoreColor);
        doc.setFont("helvetica", "bold");
        doc.text(`${p}%`, 360, y + 14);
        doc.setTextColor(60, 70, 90);
        doc.setFont("helvetica", "normal");
        doc.text(g.grade_label || "-", 450, y + 14);
        y += 20; rowAlt = !rowAlt;
      });

      // Average row
      if (avgGrade !== null) {
        doc.setFillColor(240, 243, 255);
        doc.rect(30, y, W - 60, 22, "F");
        doc.setTextColor(30, 42, 100);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.text("Overall Average", 40, y + 15);
        doc.text(`${avgGrade}%`, 360, y + 15);
        y += 22;
      }
    }

    // ── Activity Section ──
    y += 10;
    sectionTitle("Activity & Participation");
    doc.setFillColor(245, 247, 250);
    doc.roundedRect(30, y, W - 60, 50, 6, 6, "F");
    doc.setTextColor(80, 90, 110);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const actStr = `Total absences recorded: ${absentCount}  ·  Late arrivals: ${lateCount}  ·  Attendance score: ${attendancePct}%`;
    doc.text(actStr, 50, y + 20);
    doc.text(`Grades recorded across ${Object.keys(bySubject).length} subject(s) this academic year.`, 50, y + 36);
    y += 68;

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFillColor(245, 247, 250);
      doc.rect(0, doc.internal.pageSize.getHeight() - 28, W, 28, "F");
      doc.setTextColor(140, 150, 165);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text(`Confidential · ${schoolNameEn} · Page ${i} of ${pageCount}`, W / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
    }

    doc.save(`${student.full_name.replace(/\s+/g, "_")}_Performance_Report.pdf`);
    setGenerating(false); setOpen(false); setStudentId("");
  };

  return (
    <>
      <button className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl text-sm font-semibold transition-all border-2 border-stone-200 bg-white text-stone-800 hover:bg-stone-50 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed h-8 px-3 gap-1.5" onClick={() => setOpen(true)}>
        <FileDown className="h-4 w-4" /> Export PDF Report
      </button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Export Student Performance Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <p className="text-sm text-muted-foreground">
              Generates a PDF with attendance records, grade averages, and activity participation for a student.
            </p>
            <div>
              <Label>Student ID *</Label>
              <Input className="mt-1" placeholder="e.g. STU-001" value={studentId}
                onChange={e => { setStudentId(e.target.value); setError(""); }}
                onKeyDown={e => e.key === "Enter" && generate()} />
            </div>
            {error && <p className="text-sm text-destructive">{error}</p>}
          </div>
          <DialogFooter>
            <button className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl text-sm font-semibold transition-all border-2 border-stone-200 bg-white text-stone-800 hover:bg-stone-50 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed h-11 px-4" onClick={() => setOpen(false)}>Cancel</button>
            <button onClick={generate} disabled={generating || !studentId.trim()} className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl text-sm font-semibold transition-all bg-primary text-white hover:bg-primary/90 cursor-pointer shadow-lg shadow-primary/20 disabled:opacity-50 disabled:cursor-not-allowed h-11 px-4 gap-1.5">
              {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating...</> : <><FileDown className="h-4 w-4" /> Generate & Download</>}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}